name: Webpage Checker

on:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  check_webpage:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2
      
    - name: 'Check Webpage'
      run: |
        curl -s -o /dev/null https://decorous-cold-zucchini.glitch.me
